### ISSUE TITLE
Could you please implement --tile option to your code?

### ISSUE THREAD

**Issue by zelenooki87** [sunny2109/SAFMN#10]
Fantastic project but out of memorry for bigger pics.
cant upscale over 3MPX with 12GB GPU Ram
Thank you very much in advance

**Comment by sunny2109** [comment]
For the super-resolution of a large image with 2K or 4K pixels, 
we can crop the input image into patches and perform SR on each of these sub-images and then merge them together.

You can refer [this code](https://github.com/sanghyun-son/EDSR-PyTorch/blob/master/src/model/__init__.py#L116-L173) to do so.

**Comment by zelenooki87** [comment]
could you please help and more advice, cause I am not very familiar to python code.
could you please make .ipynb or .py file that can do this for me but in SAFMN project.
results are fantastic, I am very impressed, better than with swinir in most cases
thanks

**Comment by sunny2109** [comment]
Yeah, but can it be a few days later? 
I've had a paper going deadline recently. 
I expect to add this part of the code around the 15th.

**Comment by zelenooki87** [comment]
that is OK. keep hard work! 
greetz

**Comment by sunny2109** [comment]
Hello,, the code is available [here](https://github.com/sunny2109/SAFMN/blob/main/inference/inference_real_safmn.py)

You can use this script to achieve memory-efficient forward, but the output may have a checkerboard effect.
```
python inference/inference_real_safmn.py --large_input
```

**Comment by zelenooki87** [comment]
thank you very much
