### ISSUE TITLE
what data did you use for training the realworld ver. model?

### ISSUE THREAD

**Issue by anewusername77** [sunny2109/SAFMN#12]
Hi there, thanks for your great work!
I noticed your pretrained models had a 'SAFMN L real' one, how to train this model? because i want to train a 'x2 efficient real' model myself.

**Comment by sunny2109** [comment]
Hello, we are mainly following [real-esrgan](https://github.com/xinntao/Real-ESRGAN) to train our real-world model. You can refer to the setup of this repo to train the x2 Real SR.

**Comment by anewusername77** [comment]
thanks!
