### ISSUE TITLE
LAM visualization code

### ISSUE THREAD

**Issue by csguoh** [sunny2109/SAFMN#15]
Hi, authors
Thanks for your great work! The Fig.2 of LAM visualiztion is a very impressive way to demonstrate the different receptive filed between different models.  And I also want to implement this, so i wonder is it convenient for you to share the LAM visualiztion code? It will really helps a lot to me :D

**Comment by sunny2109** [comment]
hi, you can use this [colab](https://colab.research.google.com/drive/1ZodQ8CRCfHw0y6BweG9zB3YrK_lYWcDk?usp=sharing)  file to generate LAM results.

**Comment by csguoh** [comment]
Thansk you!
