### ISSUE TITLE
lightweight SR 和 classic SR 的epoch数目

### ISSUE THREAD

**Issue by bo-henry** [sunny2109/SAFMN#19]
根据提供的training log，batch_size_per_gpu=64（lightweight SR）和batch_size_per_gpu=48（classic SR）为什么训练需要的epoch一样啊？

**Comment by sunny2109** [comment]
> 根据提供的training log，batch_size_per_gpu=64（lightweight SR）和batch_size_per_gpu=48（classic SR）为什么训练需要的epoch一样啊？

你好，我们训练的时候是按iteration来算的，没有按epoch。

**Comment by bo-henry** [comment]
感谢你的回复，我观察到batch_size_per_gpu=64（lightweight SR）和batch_size_per_gpu=48（classic SR）训练的iteration都为500000，训练集相同，epoch = batchsize *iteration/样本总数，但是两者的epoch却都是22，这是为什么？

**Comment by sunny2109** [comment]
> 感谢你的回复，我观察到batch_size_per_gpu=64（lightweight SR）和batch_size_per_gpu=48（classic SR）训练的iteration都为500000，训练集相同，epoch = batchsize *iteration/样本总数，但是两者的epoch却都是22，这是为什么？

不好意思，给你造成困扰了。我检查了一下，classic sr x2/x3的log被我复制错了，是batch_size=64的。我当时训练了两个版本：batch_size=64和batch_size=48，在验证集上的结果非常接近，差距在0.03db。后面就使用了batch_size=48的setting，这样训练时间上可以少12个小时左右。

**Comment by bo-henry** [comment]
非常感谢你的回复，祝你生活愉快！
