### ISSUE TITLE
使用NTIRE-2023数据集如何设置YML文件？

### ISSUE THREAD

**Issue by GuitarZH** [sunny2109/SAFMN#20]
您好，
      感谢您的精彩论文，既有很好的创新，也很实用。我想用这个网络尝试跑这个数据集（NTIRE 2023 Efficient SR challenge），请问如何设置训练和测试的YML文件呢？

**Comment by sunny2109** [comment]
> 您好， 感谢您的精彩论文，既有很好的创新，也很实用。我想用这个网络尝试跑这个数据集（NTIRE 2023 Efficient SR challenge），请问如何设置训练和测试的YML文件呢？

您好，您可以复制一下[efficient_sr_x4.yml](https://github.com/sunny2109/SAFMN/blob/main/options/train/SAFMN/train_DF2K_X4.yml)，然后修改数据集的路径、patch_size改为96*4、iterations改为100w(比赛时用的是60w)。

**Comment by GuitarZH** [comment]
非常感谢您的帮助！
