### ISSUE TITLE
测试与验证不一致

### ISSUE THREAD

**Issue by 1016cxx** [sunny2109/SAFMN#21]
您好，我使用set5与set14作为验证集，但是在同一model上验证与测试的psnr与ssim不一致，请问这是为什么？

**Comment by sunny2109** [comment]
您好，这主要是由于使用了[ema](https://zhuanlan.zhihu.com/p/68748778)，你可以测试的时候加载ema模型或者训练更久一些，这样两者的结果就一致了。

**Comment by sunny2109** [comment]
我之前对比过，使用整图训练的结果会比patch的稍微高一点，0.05db左右，但是用整图的训练速度会慢很多。(实验不是很严格，仅供参考。)

**Comment by Feynman1999** [comment]
> 您好，这主要是由于使用了[ema](https://zhuanlan.zhihu.com/p/68748778)，你可以测试的时候加载ema模型或者训练更久一些，这样两者的结果就一致了。

请问ema策略对psnr任务有提升吗，之前只知道对gan可以效果更好
