### ISSUE TITLE
关于损失函数的消融

### ISSUE THREAD

**Issue by alexhe101** [sunny2109/SAFMN#28]
作者您好！
看到您在文中用了FFT loss，我训练了两三万iter简单试了一下，发现删掉FFT loss指标好像会有所提高，想问问您有没有验证过fft loss对完整训练流程的影响，删去fft loss会导致模型最终性能的下降吗？

**Comment by sunny2109** [comment]
您好，我们在之前的工作做了验证，使用FFT Loss在5个测试集上平均可以提高0.05dB。2、3w次iter模型波动还很大，差不多得15w次左右才能看出差距。
<img width="786" alt="Snipaste_2023-12-07_15-38-15" src="https://github.com/sunny2109/SAFMN/assets/37045074/7a8d0d10-fc8e-4c1a-bf66-bd335166d68f">
