### ISSUE TITLE
关于real-world模型

### ISSUE THREAD

**Issue by alexhe101** [sunny2109/SAFMN#32]
作者您好，请问您real-world模型还是用同样参数量的小模型，follow real-esrgan的方法训练的吗？还是有给模型参数量加大

**Comment by sunny2109** [comment]
您好，real-world模型的参数量加大到了[5.6M](https://github.com/sunny2109/SAFMN/blob/main/options/train/SAFMN/train_L_DF2K_X4.yml)，训练数据的合成方式跟real-esrgan一样，但调整了一些退化参数；训练策略跟real-esrgan有一些不同，但还是基于GAN来训的。

**Comment by alexhe101** [comment]
感谢您的解答，您有尝试过在轻量级模型上做real world训练吗 效果怎么样

**Comment by sunny2109** [comment]
> 感谢您的解答，您有尝试过在轻量级模型上做real world训练吗 效果怎么样

尝试过，结果容易欠拟合。加过蒸馏之类的技巧，有一点改善。

**Comment by alexhe101** [comment]
感谢您的解答，很有帮助

**Comment by EchoXu98** [comment]
> 您好，real-world模型的参数量加大到了[5.6M](https://github.com/sunny2109/SAFMN/blob/main/options/train/SAFMN/train_L_DF2K_X4.yml)，训练数据的合成方式跟real-esrgan一样，但调整了一些退化参数；训练策略跟real-esrgan有一些不同，但还是基于GAN来训的。

您好，您将SAFMN扩展到真实世界超分上的应用是一个非常有意思的操作，但是这里有些不明白的地方想要请教您。就我对real-esrgan的了解，其中提到了一种新的图像退化过程的方法，因此来合成模拟真实图像退化过程的数据。但是，我不太理解您这里的“基于GAN来训的”是什么意思？可能是因为我并没有阅读过GAN网络的相关文章。您应该是先使用real-esrgan中所提到的图像退化过程方法来得到训练数据，然后根据这个数据来训练自己的SAFMN网络。但是训练SAFMN的过程需要借助GAN网络吗？

**Comment by sunny2109** [comment]
> > 您好，real-world模型的参数量加大到了[5.6M](https://github.com/sunny2109/SAFMN/blob/main/options/train/SAFMN/train_L_DF2K_X4.yml)，训练数据的合成方式跟real-esrgan一样，但调整了一些退化参数；训练策略跟real-esrgan有一些不同，但还是基于GAN来训的。
> 
> 您好，您将SAFMN扩展到真实世界超分上的应用是一个非常有意思的操作，但是这里有些不明白的地方想要请教您。就我对real-esrgan的了解，其中提到了一种新的图像退化过程的方法，因此来合成模拟真实图像退化过程的数据。但是，我不太理解您这里的“基于GAN来训的”是什么意思？可能是因为我并没有阅读过GAN网络的相关文章。您应该是先使用real-esrgan中所提到的图像退化过程方法来得到训练数据，然后根据这个数据来训练自己的SAFMN网络。但是训练SAFMN的过程需要借助GAN网络吗？

是的，是您理解的这个意思。

**Comment by EchoXu98** [comment]
> > > 您好，real-world模型的参数量加大到了[5.6M](https://github.com/sunny2109/SAFMN/blob/main/options/train/SAFMN/train_L_DF2K_X4.yml)，训练数据的合成方式跟real-esrgan一样，但调整了一些退化参数；训练策略跟real-esrgan有一些不同，但还是基于GAN来训的。
> > 
> > 
> > 您好，您将SAFMN扩展到真实世界超分上的应用是一个非常有意思的操作，但是这里有些不明白的地方想要请教您。就我对real-esrgan的了解，其中提到了一种新的图像退化过程的方法，因此来合成模拟真实图像退化过程的数据。但是，我不太理解您这里的“基于GAN来训的”是什么意思？可能是因为我并没有阅读过GAN网络的相关文章。您应该是先使用real-esrgan中所提到的图像退化过程方法来得到训练数据，然后根据这个数据来训练自己的SAFMN网络。但是训练SAFMN的过程需要借助GAN网络吗？
> 
> 是的，是您理解的这个意思。

好的，谢谢您的回答。我还以为您没有回答我的问题（github上绑定的邮箱没有给我回复），所以没有第一时间表示答谢。请问在借助GAN网络训练的过程中，您的SAFMN是作为生成器模型吗？GAN网络的判别器模型是同Real-ESRGAN网络相同吗？

**Comment by sunny2109** [comment]
> > > > 您好，real-world模型的参数量加大到了[5.6M](https://github.com/sunny2109/SAFMN/blob/main/options/train/SAFMN/train_L_DF2K_X4.yml)，训练数据的合成方式跟real-esrgan一样，但调整了一些退化参数；训练策略跟real-esrgan有一些不同，但还是基于GAN来训的。
> > > 
> > > 
> > > 您好，您将SAFMN扩展到真实世界超分上的应用是一个非常有意思的操作，但是这里有些不明白的地方想要请教您。就我对real-esrgan的了解，其中提到了一种新的图像退化过程的方法，因此来合成模拟真实图像退化过程的数据。但是，我不太理解您这里的“基于GAN来训的”是什么意思？可能是因为我并没有阅读过GAN网络的相关文章。您应该是先使用real-esrgan中所提到的图像退化过程方法来得到训练数据，然后根据这个数据来训练自己的SAFMN网络。但是训练SAFMN的过程需要借助GAN网络吗？
> > 
> > 
> > 是的，是您理解的这个意思。
> 
> 好的，谢谢您的回答。我还以为您没有回答我的问题（github上绑定的邮箱没有给我回复），所以没有第一时间表示答谢。请问在借助GAN网络训练的过程中，您的SAFMN是作为生成器模型吗？GAN网络的判别器模型是同Real-ESRGAN网络相同吗？

是的

**Comment by EchoXu98** [comment]
> > > > > 您好，real-world模型的参数量加大到了[5.6M](https://github.com/sunny2109/SAFMN/blob/main/options/train/SAFMN/train_L_DF2K_X4.yml)，训练数据的合成方式跟real-esrgan一样，但调整了一些退化参数；训练策略跟real-esrgan有一些不同，但还是基于GAN来训的。
> > > > 
> > > > 
> > > > 您好，您将SAFMN扩展到真实世界超分上的应用是一个非常有意思的操作，但是这里有些不明白的地方想要请教您。就我对real-esrgan的了解，其中提到了一种新的图像退化过程的方法，因此来合成模拟真实图像退化过程的数据。但是，我不太理解您这里的“基于GAN来训的”是什么意思？可能是因为我并没有阅读过GAN网络的相关文章。您应该是先使用real-esrgan中所提到的图像退化过程方法来得到训练数据，然后根据这个数据来训练自己的SAFMN网络。但是训练SAFMN的过程需要借助GAN网络吗？
> > > 
> > > 
> > > 是的，是您理解的这个意思。
> > 
> > 
> > 好的，谢谢您的回答。我还以为您没有回答我的问题（github上绑定的邮箱没有给我回复），所以没有第一时间表示答谢。请问在借助GAN网络训练的过程中，您的SAFMN是作为生成器模型吗？GAN网络的判别器模型是同Real-ESRGAN网络相同吗？
> 
>

> > > > > 您好，real-world模型的参数量加大到了[5.6M](https://github.com/sunny2109/SAFMN/blob/main/options/train/SAFMN/train_L_DF2K_X4.yml)，训练数据的合成方式跟real-esrgan一样，但调整了一些退化参数；训练策略跟real-esrgan有一些不同，但还是基于GAN来训的。
> > > > 
> > > > 
> > > > 您好，您将SAFMN扩展到真实世界超分上的应用是一个非常有意思的操作，但是这里有些不明白的地方想要请教您。就我对real-esrgan的了解，其中提到了一种新的图像退化过程的方法，因此来合成模拟真实图像退化过程的数据。但是，我不太理解您这里的“基于GAN来训的”是什么意思？可能是因为我并没有阅读过GAN网络的相关文章。您应该是先使用real-esrgan中所提到的图像退化过程方法来得到训练数据，然后根据这个数据来训练自己的SAFMN网络。但是训练SAFMN的过程需要借助GAN网络吗？
> > > 
> > > 
> > > 是的，是您理解的这个意思。
> > 
> > 
> > 好的，谢谢您的回答。我还以为您没有回答我的问题（github上绑定的邮箱没有给我回复），所以没有第一时间表示答谢。请问在借助GAN网络训练的过程中，您的SAFMN是作为生成器模型吗？GAN网络的判别器模型是同Real-ESRGAN网络相同吗？
> 
> 是的

好的，感谢您的回复

**Comment by sunny2109** [comment]
> > 感谢您的解答，很有帮助
> 
> 您好，请问您有没有建议的，就是可以实现现实场景的轻量化超分网络呀
您好 可以看一下我们在AIM2025 EPSR Change上的[方案](https://github.com/sunny2109/SAFMN/tree/main/AIM2025_EPSR)。

**Comment by Franklin-L** [comment]
> > > 感谢您的解答，很有帮助
> > 
> > 
> > 您好，请问您有没有建议的，就是可以实现现实场景的轻量化超分网络呀
> > 您好 可以看一下我们在AIM2025 EPSR Change上的[方案](https://github.com/sunny2109/SAFMN/tree/main/AIM2025_EPSR)。

感谢前辈的解答，请问可以理解为使用SAFMN的框架但是训练的时候加入感知loss来实现real world效果吗，25年比赛的模型对我来说还是有点太大了，我目前的想法是继续减小模型大小至dim64 block调整为8，经过测试SAFMN在这个大小的速度是符合我的需求的，之前我还测试过贵团队的SMFANet，然后利用real-esgan退化管道训练效果还可以就是速度不够快，所以又关注到了SAFMN以及后续的SAFMN++模型，发现速度快了很多，所以想请教一下前辈，如果我想实现轻量化的现实场景超分，是利用SAFMN还是SAFMN++作为基础模型呢，还有就是如果模型变的特别小的话是不是很难训练出效果
