### ISSUE TITLE
如何运行3倍

### ISSUE THREAD

**Issue by xiaxiashihetun** [sunny2109/SAFMN#33]
您好，我在Google Colab上成功运行了4被超分和2倍超分模型。然后我用
if test_patch_wise:
  !python inference/inference_real_safmn.py --model_path experiments/pretrained_models/SAFMN_DF2K_x3.pth --input BSRGAN/testsets/RealSRSet --output results/SAFMN_x3 --scale 3 --large_input
else:
  !python inference/inference_real_safmn.py --model_path experiments/pretrained_models/SAFMN_DF2K_x3.pth --input BSRGAN/testsets/RealSRSet  --output results/SAFMN_x3 --scale 3
试图运行3倍超分，结果得到了“预训练模型参数不匹配”的问题。请问应该如何解决，谢谢

**Comment by sunny2109** [comment]
您好，真实场景下，我没有跑x3的模型。

**Comment by xiaxiashihetun** [comment]
好的好的，感谢~
