### ISSUE TITLE
"No object named 'RealSRModel' found in 'model' registry!"

### ISSUE THREAD

**Issue by cdy-123** [sunny2109/SAFMN#4]
I have already loaded the data and pre training model, and I encountered the following error while running the code：
Name RealSRModel_basicsr is not found, use name: RealSRModel_basicsr_basicsr!
Traceback (most recent call last):
  File "basicsr/test.py", line 45, in <module>
    test_pipeline(root_path)
  File "basicsr/test.py", line 35, in test_pipeline
    model = build_model(opt)
  File "/opt/conda/lib/python3.8/site-packages/basicsr/models/__init__.py", line 26, in build_model
    model = MODEL_REGISTRY.get(opt['model_type'])(opt)
  File "/opt/conda/lib/python3.8/site-packages/basicsr/utils/registry.py", line 71, in get
    raise KeyError(f"No object named '{name}' found in '{self._name}' registry!")
KeyError: "No object named 'RealSRModel_basicsr' found in 'model' registry!"

**Comment by sunny2109** [comment]
In test_real_img_x4.yml we are using the [RealSRModel](https://github.com/sunny2109/SAFMN/blob/main/basicsr/models/realsr_model.py) not the RealSRModel_basicsr.

 If you want to change the model_type in the configuration file, you need to add the corresponding model and register it with MODEL_REGISTRY.register().

**Comment by cdy-123** [comment]
Okay, thank you for your reply
