### ISSUE TITLE
AssertionError: An object named 'SAFMN' was already registered in 'arch' registry!的问题

### ISSUE THREAD

**Issue by bigtiezhu** [sunny2109/SAFMN#40]
您好，在使用网络时碰见这个问题：第一次完整使用网络训练：python basicsr/train.py -opt options/train/SAFMN/train_DF2K_X2.yml
后未发现异常，可以正常生成结果。但是想重新训练时，出现如下报错：AssertionError: An object named 'SAFMN' was already registered in 'arch' registry!。在train_DF2K_X2.YML中network_g->type修改为SAFMN_NITRE后报错信息仍不变，请问如何解决这个问题，感谢！

**Comment by bigtiezhu** [comment]
系统为win10，未用Linux实验，请问这是win下的问题吗？

**Comment by sunny2109** [comment]
这是因为xx_arch.py文件中注册了两个叫SAFMN方法。你是不是复制了一份？要记得修改方法名。

**Comment by bigtiezhu** [comment]
好的感谢！可能确实是复制时多复制了一份，现在问题已解决，感谢回复！
