### ISSUE TITLE
训练过程中val集的问题

### ISSUE THREAD

**Issue by bigtiezhu** [sunny2109/SAFMN#41]
孙博士您好，我有个问题需要您指导，您在 options/train/SAFMN  /train_DF2K_X2.yml中在验证集中的设置为datasets/DIV2K/DIV2K_Valid/LR_bicubic/X2，我理解的bicubic可以通过matlab或者opencv操作，请问后面的X2要放什么内容，是和训练集一样把图片分辨率降低后的图片放到这个文件夹下吗？

还有一个问题是在进行测试时，train_DF2K_x2.yml文件夹内：
datasets:
  test_1:  # the 1st test dataset
    name: Set5
    type: PairedImageDataset
    dataroot_gt: datasets/Benchmarks/Set5/HR
    dataroot_lq: datasets/Benchmarks/Set5/LR_bicubic/X2
    filename_tmpl: '{}x2'
datasets/Benchmarks/Set5/LR_bicubic/X2存放的内容是什么？
谢谢您的指导！

**Comment by sunny2109** [comment]
dataroot_gt是GT图像存放的路径， dataroot_lq是对应的下采样图片的存放路径。为了好区分不同的下采样倍率图片，在命名的时候加了对应的下采样因子，如'---x2.png'。

**Comment by bigtiezhu** [comment]
好的，感谢您！
