### ISSUE TITLE
Uncertainty-based loss

### ISSUE THREAD

**Issue by muslll** [sunny2109/SAFMN#49]
Hi, thanks for your research. On the AIS 2024 submission, it is said that "the proposed SAFMN++ is trained by minimizing a combination of the uncertainty-based MSE loss and FFT-based L1 loss ". However, I couldn't find those in this repository. Do you plan on releasing it as well?
Thanks in advance.

**Comment by sunny2109** [comment]
Hi, sorry for such a late reply.
The implementation of uncertainty loss can be found in the featup](https://github.com/mhamilton723/FeatUp) repo.

**Comment by muslll** [comment]
Thanks!
