### ISSUE TITLE
No Pretrained Models Provided for AIS2024-RTSR

### ISSUE THREAD

**Issue by FahadMahdi** [sunny2109/SAFMN#53]
For light_SAFMN++, no pretrained models were given. Can you please provide pretrained models to facilitate further research and development?

**Comment by sunny2109** [comment]
Hello, you can download the pre-trained model [here]( https://github.com/sunny2109/SAFMN/tree/main/AIS2024-RTSR/pretrained_model)

**Comment by FahadMahdi** [comment]
Thank you very much.

**Comment by FahadMahdi** [comment]
Thank you very much.
