### ISSUE TITLE
关于复现训练 light_safmnpp 效果和预训练模型有出入的问题

### ISSUE THREAD

**Issue by zephyRMountain** [sunny2109/SAFMN#58]
![light_safmnpp_contrast](https://github.com/user-attachments/assets/cc194076-29f7-4d19-ae87-39555d21cf18)
您好，问题如题所示。dataset使用DIV2K，loss使用了您配置文件的L1、MSE、fft，gt_size无法像您AIS24报告中所提设置成1280，因DIV2K有些 图片下缩放4倍后无法达到分辨率要求。训练出的模型的边缘效果和您的预训练模型无法相当，差距较大，请问可能是什么原因导致的呢？ 或者您可否提供AIS24，light_safmnpp的训练代码，让我逐一排查呢，感谢！

**Comment by sunny2109** [comment]
您好，可能是不同的退化类型造成性能差异，AIS这个比赛用的退化是lanczos + avif压缩。训练的patch_size影响不是很大，训练代码跟之前SAFMN的一致。

**Comment by zephyRMountain** [comment]
十分感谢。
