### ISSUE TITLE
关于复现效果达不到预训练模型效果的问题

### ISSUE THREAD

**Issue by xtylyq** [sunny2109/SAFMN#59]
![对比（右-safmnpp预训练）](https://github.com/user-attachments/assets/d3b16ba1-b1e1-4c8c-8cd3-2d0c398810a8)

你好，感谢带来精彩的工作！
我想复现AIS24模型时，发现我自己训练的模型（左）达不到您预训练模型的效果（右），我使用的同模型结构，DIV2K bicubicx4，未对数据集使用退化。请问可能是什么原因呢，您能公布一下AIS24竞赛的训练代码吗，感谢！

**Comment by sunny2109** [comment]
您好，可能是不同的退化类型造成性能差异，AIS这个比赛用的退化是lanczos + avif压缩。训练代码跟之前的原始版本SAFMN的代码一样。

**Comment by xtylyq** [comment]
感谢！
