### ISSUE TITLE
AIS2024模型复现

### ISSUE THREAD

**Issue by zephyRMountain** [sunny2109/SAFMN#61]
您好，感谢带来精彩工作。
我在复现您AIS2024的pretrain模型light_safmnpp时，始终达不到您提供的权重模型的效果。差距主要表现在锯齿和平滑度方面。
我已在DIV2K的数据集上使用了官方提供的lanczos+libsvtav1 qp 31下缩放x4来预处理dataset，其余训练配置使用您提供的默认x4.yml.

请问是什么原因导致的呢？如何才能达到如此平滑的x4效果？
![contrast](https://github.com/user-attachments/assets/a29bf4e6-e1c0-4d07-b195-2551a3aec80e)

**Comment by sunny2109** [comment]
您好 在训练这个模型的时候我们使用了multi_patch的策略，最大的LR patch_size是160，在最后一轮微调的时候用的是L2 loss；训练数据用的是DF2K，合成退化的时候qp是从[31, 39, 47, 55]随机取的。

**Comment by zephyRMountain** [comment]
您好，感谢
